theme: jekyll-theme-chirpy
lang: en
timezone: Europe/Prague
title: Ephemeris
tagline: A blog about me and my interests
description: >-
  A blog about me and my interests
url: "https://blog.hangerthem.com"

github:
  username: HangerThem

twitter:
  username: hangerthem

instagram:
  username: ferda_borisjuk

social:
  name: Frank Borisjuk
  email: f.borisjuk@hangerthem.com
  links:
    - https://twitter.com/hangethem
    - https://github.com/hangerthem
    - https://www.instagram.com/ferda_borisjuk/

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:

pageviews:
  provider:

theme_mode:

cdn:

avatar: /assets/img/avatar.png

social_preview_image: 

toc: true

comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname:
  utterances:
    repo:
    issue_term: # < url | pathname | title | ...>
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled: false
    env: # [development | production]

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
